---
- name: create users
  become: true
  hosts: all
#  vars:
#    pp: 'UX4aHjHe.Q'
  vars_files:
    users-list.yml
  tasks:
    - name: create the file
      debug: 
        msg: "{{ lookup('password','/tmp/' + item.key + '_file length=10' ) }}"
      with_dict: "{{ users }}"
    - name: show
      debug:
        msg: "pass: {{ lookup('file','/tmp/' + item.key + '_file') }}"
      with_dict: "{{ users }}"
    - name: create user
      user:
        name: "{{ item.key }}"
        password: "{{ lookup('file','/tmp/' + item.key + '_file') | password_hash('sha512') }}"
      register: p
      with_dict: "{{ users }}"
#    - name: really remove
#      shell: "rm -rf /home/{{ item.key }}"
#      with_dict: "{{ users }}"
         
#      when: item.key == 'bob'
#      no_log: false
#    - name: show p
#      debug:
#        msg: "{{ p }}"
#      when: inventory_hostname == 'node5'
#    - name: create user
#      user:
#        name: "{{ item.key }}"
#        password: "{{ pp | password_hash('sha512')}}"
#      register: p
#      with_dict: "{{ users }}"
#      when: item.key == 'bob' and inventory_hostname == 'node5'
